version: '3.9'

services:
  web:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    command: gunicorn devtest.config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app:ro # Mount project as read-only
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      DJANGO_DEBUG: "False"
    networks:
      - backend

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file: .env
    networks:
      - backend

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    command: redis-server --port 6380
    restart: unless-stopped
    networks:
      - backend

  worker:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    command: celery -A devtest.config.celery worker --loglevel=info
    volumes:
      - .:/app:ro
    working_dir: /app
    depends_on:
      - redis
      - db
    env_file: .env
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
