"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
base_path = Path(__file__).resolve().parent.parent.parent

# Load the single environment file
env_file = base_path / '.devcontainer/.env'
load_dotenv(dotenv_path=env_file)

# Auto-detect environment and set appropriate database host
def get_db_host():
    """
    Auto-detect the environment and return the appropriate database host.

    Detection logic:
    - If running in a Docker container with docker-compose, use 'db'
    - If running in devcontainer or locally, use 'localhost'
    """
    # Check if we're in a docker-compose environment
    # Docker-compose sets up a network where services can reach each other by service name
    if os.path.exists('/.dockerenv'):
        # We're in a Docker container
        # Check if we can resolve 'db' hostname (docker-compose)
        import socket
        try:
            socket.gethostbyname('db')
            return 'db'  # docker-compose environment
        except socket.gaierror:
            return 'localhost'  # devcontainer or other Docker environment
    else:
        return 'localhost'  # running locally

# Set the database host based on environment detection
DB_HOST_AUTO = get_db_host()

# Auto-detect Redis host
def get_redis_host():
    """
    Auto-detect the environment and return the appropriate Redis host.

    Detection logic:
    - If running in a Docker container with docker-compose, use 'redis'
    - If running in devcontainer or locally, use 'localhost'
    """
    # Check if we're in a docker-compose environment
    if os.path.exists('/.dockerenv'):
        # We're in a Docker container
        # Check if we can resolve 'redis' hostname (docker-compose)
        import socket
        try:
            socket.gethostbyname('redis')
            return 'redis'  # docker-compose environment
        except socket.gaierror:
            return 'localhost'  # devcontainer or other Docker environment
    else:
        return 'localhost'  # running locally

# Set the Redis host based on environment detection
REDIS_HOST_AUTO = get_redis_host()

# Helper function to build URLs with correct host
def get_redis_url():
    """Get Redis URL with auto-detected host."""
    redis_port = os.getenv("REDIS_PORT", "6380")
    return f"redis://{REDIS_HOST_AUTO}:{redis_port}/0"

def get_database_url():
    """Get Database URL with auto-detected host."""
    db_user = os.getenv("DB_USER", "postgres")
    db_password = os.getenv("DB_PASSWORD", "postgres")
    db_name = os.getenv("DB_NAME", "postgres")
    db_port = os.getenv("DB_PORT", "5433")
    return f"postgres://{db_user}:{db_password}@{DB_HOST_AUTO}:{db_port}/{db_name}"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ij$iz0b+6!r9s#0)crd_7kj4#apbbf3v$5yiqqphi&=_v#06wz"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "devtest.app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "devtest.config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "devtest.config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "mydb"),
        "USER": os.getenv("DB_USER", "myuser"),
        "PASSWORD": os.getenv("DB_PASSWORD", "mypassword"),
        "HOST": DB_HOST_AUTO,  # Use auto-detected host
        "PORT": os.getenv("DB_PORT", "5433"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery Configuration
CELERY_BROKER_URL = get_redis_url()
CELERY_RESULT_BACKEND = get_redis_url()
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
