name: Download env file
on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Write .env from secret
        run: echo "$ENV_FILE" > .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
      - name: Upload .env artifact
        uses: actions/upload-artifact@v4
        with:
          name: env
          path: .env

